apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mini-app
  template:
    metadata:
      labels:
        app: mini-app
    spec:
      containers:
      - name: mini-app
        image: sl33pycl0ud/mini-app:latest
        ports:
        - containerPort: 5001
